### ISSUE TITLE
Unindented comment in the generator scripts

### ISSUE THREAD

**Issue by naumb** [tuc-osg/osg-exam#6]
Lualatex throws an error when trying to build the exam. This happens independently of the chosen mode:

```
LaTeX Warning: Writing file `./main.gen.py'.


  File "main.gen.py", line 11
    '''
      ^
IndentationError: expected an indented block
```

It seems there is an unindented comment in the `genexam` function which is causing this error.

**Comment by naumb** [comment]
#10

**Comment by werner-matthias** [comment]
That seems to be an editor problem. Please don't use tab stops!
