### ISSUE TITLE
Invalid escape sequence in "individually"-mode

### ISSUE THREAD

**Issue by naumb** [tuc-osg/osg-exam#8]
When using the "individually" mode to generate a personalized exam and the `seat` option isn't set in the document, I get the following error:

```
[\directlua]:1: invalid escape sequence near '\p'.
<argument> ...xjob ' '\osgexam@outpath ' '\oex@mode ' True")}

l.361 }
```

If, however, the `seat` option is set to `true`, the generation works as intended.

**Comment by werner-matthias** [comment]
Solved in 129cd59
